### ISSUE TITLE
What is the password for the root user in the passwd file?

### ISSUE THREAD

**Issue by kododake** [m-labs/openwrt-milkymist#1]
I bought a TPLink router, and I want to access the kernel of the router using SSH, so I found this page from MD5 of the passwd file in the GPL code on the official TPLink page.
[passwd](https://github.com/m-labs/openwrt-milkymist/blob/master/package/ead/src/passwd)
Can you please tell me the password for the root user in this passwd file?
I would appreciate it if you could reply to me.

**Comment by kdodake** [comment]
I bought a TPLink router, and I want to access the kernel of the router using SSH, so I found this page from MD5 of the passwd file in the GPL code on the official TPLink page.
https://github.com/m-labs/openwrt-milkymist/blob/master/package/ead/src/passwd
Can you please tell me the password for the root user in this passwd file?
I would appreciate it if you could reply to me.
